GITMODULES_FILE_PATH = '.gitmodules'
GITMODULES_PATH_VAR_EXTRACT = '\tpath = '

HELP_COMMAND = '--help'
HELP_COMMAND_SHORT = '-h'
VERBOSE_COMMAND = '--verbose'
VERBOSE_COMMAND_SHORT = '-v'
FORCE_SUBMODULE_COMMAND = '--full'
FORCE_SUBMODULE_COMMAND_SHORT = '-f'
ONLY_SUBMODULE_COMMAND = '--submodule'
ONLY_SUBMODULE_COMMAND_SHORT = '-s'

PREMAKE_UNPACK_PATH = './tools/thirdparty/premake/'
PREMAKE_PACKED_PATH = './buildsystem/premakebuilds/'
PREMAKE_WINDOWS_ZIP_FILE = 'premake-5.0.0-alpha16-windows.zip'
PREMAKE_LINUX_TAR_FILE = 'premake-5.0.0-alpha16-linux.tar.gz'
PREMAKE_RPI_TAR_FILE = 'premake-5.0.0-alpha16-rpi.tar.gz'
